<a href="https://colab.research.google.com/github/Tejanjanidevi/FML/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **importing pandas**

In [1]:
import pandas as pd
import numpy as np

# **pandas Data Structures**



*   Series
*   DataFrame

# **Series**

A Series is simiiar to one dimensional Array. It can store data of any type and is mutable.

In [2]:
s1 = pd.Series([1,2,3,4])
print(s1)

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
# A Series may also be created from a numpy array.
# Let us create a numpy array then convert it into a Pandas Series:

fruits = np.array(['apple','orange','mango','pear'])
series2 = pd.Series(fruits)
print(series2)

0     apple
1    orange
2     mango
3      pear
dtype: object

# **DataFrame**

In [4]:
df1 = pd.DataFrame({
    "C1": [1, 4, 8, 7, 9],
    "C2": ['a', 'column', 'with', 'a', 'string'],
    "C3": [1.23, 23.5, 45.6, 32.1234, 89.453],
    "C4": [True, False, True, False, True]
})

In [5]:
print(df1)

   C1      C2       C3     C4
0   1       a   1.2300   True
1   4  column  23.5000  False
2   8    with  45.6000   True
3   7       a  32.1234  False
4   9  string  89.4530   True

In [7]:
# It is possible for us to create a DataFrame from a list or even a set of lists.
mylist = [4, 8, 12, 16, 20]
df2 = pd.DataFrame(mylist)
print(df2)

    0
0   4
1   8
2  12
3  16
4  20

In [8]:
# It is possible for us to create a DataFrame from a list or even a set of lists.
mylist = [4, 8, 12, 16, 20]
df2 = pd.DataFrame(mylist)
print(df2)

    0
0   4
1   8
2  12
3  16
4  20

In [10]:
items = [['Phone', 2000], ['TV', 1500], ['Radio', 800]]
df3 = pd.DataFrame(items)
print(df3)

       0     1
0  Phone  2000
1     TV  1500
2  Radio   800

In [11]:
items = [['Phone', 2000], ['TV', 1500], ['Radio', 800]]
df4 = pd.DataFrame(items, columns=['Item', 'Price'], dtype=float)
print(df4)

    Item   Price
0  Phone  2000.0
1     TV  1500.0
2  Radio   800.0

<ipython-input-11-0755eeebd180>:2: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  df4 = pd.DataFrame(items, columns=['Item', 'Price'], dtype=float)

# **Importing Data**

In [12]:
data = pd.read_excel("/content/drive/MyDrive/Student Marks.xlsx")
print(data)

    Roll No Name of the Student  C Language  Java  Python  Machine Learning  \
0       201                Hema          86    86      91                95
1       202                Hari          93    93      83                78
2       203                 Ram          89    89      95                92
3       204               Latha          98    98      96                77
4       205                Rani          87    87      87                92
5       206              Jyothi          89    89      82                69
6       207             Krishna          90    94      85                68
7       208                Raju          94    95      88                78
8       209              Suresh          95    96      99                91
9       214              Bhavya          69    92      93                82
10      210             Sandhya          78    87      87                83
11      211             Sameera          92    82      77                95
12      212            Santhosh          77    85      82                96
13      213              Anusri          92    88      86                87
14      214              Bhavya          69    92      93                82
15      216             Lakshmi          68    77      89                85
16      217              Ravali          78    87      98                88
17      218               Meena          91    82      87                99
18      207             Krishna          90    94      85                68
19      219              Kalyan          83    85      89                87
20      226            Bhargavi          96    87      88                89
21      220              Charan          87    88      94                73
22      221               Arjun          89    99      95                92
23      222                Niha          65    87      96                91
24      223             Neeraja          74    85      87                93
25      224                Devi          94    88      82                86
26      225               Bindu          95    99      85                93
27      226            Bhargavi          96    87      88                89
28      227             Nandini          87    73      92                98
29      228             Syamala          82    92      77                87
30      229             Sumanth          85    91      82                89
31      230             Subhash          88    93      85                94
32      231              Devika          99    86      88                95
33      232                Isha          87    93      99                96
34      233              Apsara          73    89      87                87
35      234             Ankitha          66    94      85                82
36      235            Anuradha          84    95      88                85
37      236             Jeevana          85    78      99                88
38      237              Ganesh          96    92      87                92
39      238           Poorinima          92    77      73                77
40      239            Manjusha          91    90      92                97
41      240            Nikhitha          93    68      91                69

    Data Science  Artificial Intelligence  Unnamed: 8 Unnamed: 9
0             86                       69         NaN        NaN
1             93                       70         NaN        NaN
2             89                       86         NaN        NaN
3             98                       90         NaN        NaN
4             87                       96         NaN        NaN
5             89                       86         NaN          =
6             94                       93         NaN        NaN
7             95                       89         NaN        NaN
8             96                       98         NaN        NaN
9             92                       96         NaN        NaN
10            87                       87         NaN        NaN
11            82                       89         NaN        NaN
12            85                       94         NaN        NaN
13            88                       95         NaN        NaN
14            92                       96         NaN        NaN
15            77                       87         NaN        NaN
16            91                       82         NaN        NaN
17            83                       85         NaN        NaN
18            94                       93         NaN        NaN
19            87                       88         NaN        NaN
20            87                       93         NaN        NaN
21            89                       92         NaN        NaN
22            65                       77         NaN        NaN
23            74                       88         NaN        NaN
24            94                       99         NaN        NaN
25            95                       87         NaN        NaN
26            96                       86         NaN        NaN
27            87                       93         NaN        NaN
28            82                       89         NaN        NaN
29            85                       98         NaN        NaN
30            88                       87         NaN        NaN
31            99                       89         NaN        NaN
32            87                       90         NaN        NaN
33            66                       94         NaN        NaN
34            88                       95         NaN        NaN
35            77                       78         NaN        NaN
36            99                       92         NaN        NaN
37            59                       77         NaN        NaN
38            60                       92         NaN        NaN
39            56                       69         NaN        NaN
40            70                       68         NaN        NaN
41            85                       78         NaN        NaN

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
data.head()

,Roll No,Name of the Student,C Language,Java,Python,Machine Learning,Data Science,Artificial Intelligence,Unnamed: 8,Unnamed: 9
0,201,Hema,86,86,91,95,86,69,NaN,NaN
1,202,Hari,93,93,83,78,93,70,NaN,NaN
2,203,Ram,89,89,95,92,89,86,NaN,NaN
3,204,Latha,98,98,96,77,98,90,NaN,NaN
4,205,Rani,87,87,87,92,87,96,NaN,NaN

In [15]:
data.tail()

,Roll No,Name of the Student,C Language,Java,Python,Machine Learning,Data Science,Artificial Intelligence,Unnamed: 8,Unnamed: 9
37,236,Jeevana,85,78,99,88,59,77,NaN,NaN
38,237,Ganesh,96,92,87,92,60,92,NaN,NaN
39,238,Poorinima,92,77,73,77,56,69,NaN,NaN
40,239,Manjusha,91,90,92,97,70,68,NaN,NaN
41,240,Nikhitha,93,68,91,69,85,78,NaN,NaN

Iterrows()

Iterrows displayed all columns in row order.

In [16]:
data

,Roll No,Name of the Student,C Language,Java,Python,Machine Learning,Data Science,Artificial Intelligence,Unnamed: 8,Unnamed: 9
0,201,Hema,86,86,91,95,86,69,NaN,NaN
1,202,Hari,93,93,83,78,93,70,NaN,NaN
2,203,Ram,89,89,95,92,89,86,NaN,NaN
3,204,Latha,98,98,96,77,98,90,NaN,NaN
4,205,Rani,87,87,87,92,87,96,NaN,NaN
5,206,Jyothi,89,89,82,69,89,86,NaN,=
6,207,Krishna,90,94,85,68,94,93,NaN,NaN
7,208,Raju,94,95,88,78,95,89,NaN,NaN
8,209,Suresh,95,96,99,91,96,98,NaN,NaN
9,214,Bhavya,69,92,93,82,92,96,NaN,NaN
10,210,Sandhya,78,87,87,83,87,87,NaN,NaN
11,211,Sameera,92,82,77,95,82,89,NaN,NaN
12,212,Santhosh,77,85,82,96,85,94,NaN,NaN
13,213,Anusri,92,88,86,87,88,95,NaN,NaN
14,214,Bhavya,69,92,93,82,92,96,NaN,NaN
15,216,Lakshmi,68,77,89,85,77,87,NaN,NaN
16,217,Ravali,78,87,98,88,91,82,NaN,NaN
17,218,Meena,91,82,87,99,83,85,NaN,NaN
18,207,Krishna,90,94,85,68,94,93,NaN,NaN
19,219,Kalyan,83,85,89,87,87,88,NaN,NaN
20,226,Bhargavi,96,87,88,89,87,93,NaN,NaN
21,220,Charan,87,88,94,73,89,92,NaN,NaN
22,221,Arjun,89,99,95,92,65,77,NaN,NaN
23,222,Niha,65,87,96,91,74,88,NaN,NaN
24,223,Neeraja,74,85,87,93,94,99,NaN,NaN
25,224,Devi,94,88,82,86,95,87,NaN,NaN
26,225,Bindu,95,99,85,93,96,86,NaN,NaN
27,226,Bhargavi,96,87,88,89,87,93,NaN,NaN
28,227,Nandini,87,73,92,98,82,89,NaN,NaN
29,228,Syamala,82,92,77,87,85,98,NaN,NaN
30,229,Sumanth,85,91,82,89,88,87,NaN,NaN
31,230,Subhash,88,93,85,94,99,89,NaN,NaN
32,231,Devika,99,86,88,95,87,90,NaN,NaN
33,232,Isha,87,93,99,96,66,94,NaN,NaN
34,233,Apsara,73,89,87,87,88,95,NaN,NaN
35,234,Ankitha,66,94,85,82,77,78,NaN,NaN
36,235,Anuradha,84,95,88,85,99,92,NaN,NaN
37,236,Jeevana,85,78,99,88,59,77,NaN,NaN
38,237,Ganesh,96,92,87,92,60,92,NaN,NaN
39,238,Poorinima,92,77,73,77,56,69,NaN,NaN
40,239,Manjusha,91,90,92,97,70,68,NaN,NaN
41,240,Nikhitha,93,68,91,69,85,78,NaN,NaN

In [17]:
for rec in data.iterrows():
  print(rec)

(0, Roll No                     201
Name of the Student        Hema
C Language                   86
Java                         86
Python                       91
Machine Learning             95
Data Science                 86
Artificial Intelligence      69
Unnamed: 8                  NaN
Unnamed: 9                  NaN
Name: 0, dtype: object)
(1, Roll No                     202
Name of the Student        Hari
C Language                   93
Java                         93
Python                       83
Machine Learning             78
Data Science                 93
Artificial Intelligence      70
Unnamed: 8                  NaN
Unnamed: 9                  NaN
Name: 1, dtype: object)
(2, Roll No                    203
Name of the Student        Ram
C Language                  89
Java                        89
Python                      95
Machine Learning            92
Data Science                89
Artificial Intelligence     86
Unnamed: 8                 NaN
Unnamed: 9                 NaN
Name: 2, dtype: object)
(3, Roll No                      204
Name of the Student        Latha
C Language                    98
Java                          98
Python                        96
Machine Learning              77
Data Science                  98
Artificial Intelligence       90
Unnamed: 8                   NaN
Unnamed: 9                   NaN
Name: 3, dtype: object)
(4, Roll No                     205
Name of the Student        Rani
C Language                   87
Java                         87
Python                       87
Machine Learning             92
Data Science                 87
Artificial Intelligence      96
Unnamed: 8                  NaN
Unnamed: 9                  NaN
Name: 4, dtype: object)
(5, Roll No                       206
Name of the Student        Jyothi
C Language                     89
Java                           89
Python                         82
Machine Learning               69
Data Science                   89
Artificial Intelligence        86
Unnamed: 8                    NaN
Unnamed: 9                      =
Name: 5, dtype: object)
(6, Roll No                        207
Name of the Student        Krishna
C Language                      90
Java                            94
Python                          85
Machine Learning                68
Data Science                    94
Artificial Intelligence         93
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 6, dtype: object)
(7, Roll No                     208
Name of the Student        Raju
C Language                   94
Java                         95
Python                       88
Machine Learning             78
Data Science                 95
Artificial Intelligence      89
Unnamed: 8                  NaN
Unnamed: 9                  NaN
Name: 7, dtype: object)
(8, Roll No                       209
Name of the Student        Suresh
C Language                     95
Java                           96
Python                         99
Machine Learning               91
Data Science                   96
Artificial Intelligence        98
Unnamed: 8                    NaN
Unnamed: 9                    NaN
Name: 8, dtype: object)
(9, Roll No                       214
Name of the Student        Bhavya
C Language                     69
Java                           92
Python                         93
Machine Learning               82
Data Science                   92
Artificial Intelligence        96
Unnamed: 8                    NaN
Unnamed: 9                    NaN
Name: 9, dtype: object)
(10, Roll No                        210
Name of the Student        Sandhya
C Language                      78
Java                            87
Python                          87
Machine Learning                83
Data Science                    87
Artificial Intelligence         87
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 10, dtype: object)
(11, Roll No                        211
Name of the Student        Sameera
C Language                      92
Java                            82
Python                          77
Machine Learning                95
Data Science                    82
Artificial Intelligence         89
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 11, dtype: object)
(12, Roll No                         212
Name of the Student        Santhosh
C Language                       77
Java                             85
Python                           82
Machine Learning                 96
Data Science                     85
Artificial Intelligence          94
Unnamed: 8                      NaN
Unnamed: 9                      NaN
Name: 12, dtype: object)
(13, Roll No                       213
Name of the Student        Anusri
C Language                     92
Java                           88
Python                         86
Machine Learning               87
Data Science                   88
Artificial Intelligence        95
Unnamed: 8                    NaN
Unnamed: 9                    NaN
Name: 13, dtype: object)
(14, Roll No                       214
Name of the Student        Bhavya
C Language                     69
Java                           92
Python                         93
Machine Learning               82
Data Science                   92
Artificial Intelligence        96
Unnamed: 8                    NaN
Unnamed: 9                    NaN
Name: 14, dtype: object)
(15, Roll No                        216
Name of the Student        Lakshmi
C Language                      68
Java                            77
Python                          89
Machine Learning                85
Data Science                    77
Artificial Intelligence         87
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 15, dtype: object)
(16, Roll No                       217
Name of the Student        Ravali
C Language                     78
Java                           87
Python                         98
Machine Learning               88
Data Science                   91
Artificial Intelligence        82
Unnamed: 8                    NaN
Unnamed: 9                    NaN
Name: 16, dtype: object)
(17, Roll No                      218
Name of the Student        Meena
C Language                    91
Java                          82
Python                        87
Machine Learning              99
Data Science                  83
Artificial Intelligence       85
Unnamed: 8                   NaN
Unnamed: 9                   NaN
Name: 17, dtype: object)
(18, Roll No                        207
Name of the Student        Krishna
C Language                      90
Java                            94
Python                          85
Machine Learning                68
Data Science                    94
Artificial Intelligence         93
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 18, dtype: object)
(19, Roll No                       219
Name of the Student        Kalyan
C Language                     83
Java                           85
Python                         89
Machine Learning               87
Data Science                   87
Artificial Intelligence        88
Unnamed: 8                    NaN
Unnamed: 9                    NaN
Name: 19, dtype: object)
(20, Roll No                         226
Name of the Student        Bhargavi
C Language                       96
Java                             87
Python                           88
Machine Learning                 89
Data Science                     87
Artificial Intelligence          93
Unnamed: 8                      NaN
Unnamed: 9                      NaN
Name: 20, dtype: object)
(21, Roll No                       220
Name of the Student        Charan
C Language                     87
Java                           88
Python                         94
Machine Learning               73
Data Science                   89
Artificial Intelligence        92
Unnamed: 8                    NaN
Unnamed: 9                    NaN
Name: 21, dtype: object)
(22, Roll No                      221
Name of the Student        Arjun
C Language                    89
Java                          99
Python                        95
Machine Learning              92
Data Science                  65
Artificial Intelligence       77
Unnamed: 8                   NaN
Unnamed: 9                   NaN
Name: 22, dtype: object)
(23, Roll No                     222
Name of the Student        Niha
C Language                   65
Java                         87
Python                       96
Machine Learning             91
Data Science                 74
Artificial Intelligence      88
Unnamed: 8                  NaN
Unnamed: 9                  NaN
Name: 23, dtype: object)
(24, Roll No                        223
Name of the Student        Neeraja
C Language                      74
Java                            85
Python                          87
Machine Learning                93
Data Science                    94
Artificial Intelligence         99
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 24, dtype: object)
(25, Roll No                     224
Name of the Student        Devi
C Language                   94
Java                         88
Python                       82
Machine Learning             86
Data Science                 95
Artificial Intelligence      87
Unnamed: 8                  NaN
Unnamed: 9                  NaN
Name: 25, dtype: object)
(26, Roll No                      225
Name of the Student        Bindu
C Language                    95
Java                          99
Python                        85
Machine Learning              93
Data Science                  96
Artificial Intelligence       86
Unnamed: 8                   NaN
Unnamed: 9                   NaN
Name: 26, dtype: object)
(27, Roll No                         226
Name of the Student        Bhargavi
C Language                       96
Java                             87
Python                           88
Machine Learning                 89
Data Science                     87
Artificial Intelligence          93
Unnamed: 8                      NaN
Unnamed: 9                      NaN
Name: 27, dtype: object)
(28, Roll No                        227
Name of the Student        Nandini
C Language                      87
Java                            73
Python                          92
Machine Learning                98
Data Science                    82
Artificial Intelligence         89
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 28, dtype: object)
(29, Roll No                        228
Name of the Student        Syamala
C Language                      82
Java                            92
Python                          77
Machine Learning                87
Data Science                    85
Artificial Intelligence         98
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 29, dtype: object)
(30, Roll No                        229
Name of the Student        Sumanth
C Language                      85
Java                            91
Python                          82
Machine Learning                89
Data Science                    88
Artificial Intelligence         87
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 30, dtype: object)
(31, Roll No                        230
Name of the Student        Subhash
C Language                      88
Java                            93
Python                          85
Machine Learning                94
Data Science                    99
Artificial Intelligence         89
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 31, dtype: object)
(32, Roll No                       231
Name of the Student        Devika
C Language                     99
Java                           86
Python                         88
Machine Learning               95
Data Science                   87
Artificial Intelligence        90
Unnamed: 8                    NaN
Unnamed: 9                    NaN
Name: 32, dtype: object)
(33, Roll No                     232
Name of the Student        Isha
C Language                   87
Java                         93
Python                       99
Machine Learning             96
Data Science                 66
Artificial Intelligence      94
Unnamed: 8                  NaN
Unnamed: 9                  NaN
Name: 33, dtype: object)
(34, Roll No                       233
Name of the Student        Apsara
C Language                     73
Java                           89
Python                         87
Machine Learning               87
Data Science                   88
Artificial Intelligence        95
Unnamed: 8                    NaN
Unnamed: 9                    NaN
Name: 34, dtype: object)
(35, Roll No                        234
Name of the Student        Ankitha
C Language                      66
Java                            94
Python                          85
Machine Learning                82
Data Science                    77
Artificial Intelligence         78
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 35, dtype: object)
(36, Roll No                         235
Name of the Student        Anuradha
C Language                       84
Java                             95
Python                           88
Machine Learning                 85
Data Science                     99
Artificial Intelligence          92
Unnamed: 8                      NaN
Unnamed: 9                      NaN
Name: 36, dtype: object)
(37, Roll No                        236
Name of the Student        Jeevana
C Language                      85
Java                            78
Python                          99
Machine Learning                88
Data Science                    59
Artificial Intelligence         77
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 37, dtype: object)
(38, Roll No                       237
Name of the Student        Ganesh
C Language                     96
Java                           92
Python                         87
Machine Learning               92
Data Science                   60
Artificial Intelligence        92
Unnamed: 8                    NaN
Unnamed: 9                    NaN
Name: 38, dtype: object)
(39, Roll No                          238
Name of the Student        Poorinima
C Language                        92
Java                              77
Python                            73
Machine Learning                  77
Data Science                      56
Artificial Intelligence           69
Unnamed: 8                       NaN
Unnamed: 9                       NaN
Name: 39, dtype: object)
(40, Roll No                         239
Name of the Student        Manjusha
C Language                       91
Java                             90
Python                           92
Machine Learning                 97
Data Science                     70
Artificial Intelligence          68
Unnamed: 8                      NaN
Unnamed: 9                      NaN
Name: 40, dtype: object)
(41, Roll No                         240
Name of the Student        Nikhitha
C Language                       93
Java                             68
Python                           91
Machine Learning                 69
Data Science                     85
Artificial Intelligence          78
Unnamed: 8                      NaN
Unnamed: 9                      NaN
Name: 41, dtype: object)

UNDERSTANDING LOC[](stop index included)

*data_frame.loc[row_number]

*data_frame.loc[row_number,[column_name,...]]

*data_frame.loc[start:stop]

*data_frame.loc[start:stop,"column_name"]

*data_frame.loc[start:stop,["column_1,column_2,..."]]

loc()

  stop index value also included

   column name must indicated

In [18]:
data

,Roll No,Name of the Student,C Language,Java,Python,Machine Learning,Data Science,Artificial Intelligence,Unnamed: 8,Unnamed: 9
0,201,Hema,86,86,91,95,86,69,NaN,NaN
1,202,Hari,93,93,83,78,93,70,NaN,NaN
2,203,Ram,89,89,95,92,89,86,NaN,NaN
3,204,Latha,98,98,96,77,98,90,NaN,NaN
4,205,Rani,87,87,87,92,87,96,NaN,NaN
5,206,Jyothi,89,89,82,69,89,86,NaN,=
6,207,Krishna,90,94,85,68,94,93,NaN,NaN
7,208,Raju,94,95,88,78,95,89,NaN,NaN
8,209,Suresh,95,96,99,91,96,98,NaN,NaN
9,214,Bhavya,69,92,93,82,92,96,NaN,NaN
10,210,Sandhya,78,87,87,83,87,87,NaN,NaN
11,211,Sameera,92,82,77,95,82,89,NaN,NaN
12,212,Santhosh,77,85,82,96,85,94,NaN,NaN
13,213,Anusri,92,88,86,87,88,95,NaN,NaN
14,214,Bhavya,69,92,93,82,92,96,NaN,NaN
15,216,Lakshmi,68,77,89,85,77,87,NaN,NaN
16,217,Ravali,78,87,98,88,91,82,NaN,NaN
17,218,Meena,91,82,87,99,83,85,NaN,NaN
18,207,Krishna,90,94,85,68,94,93,NaN,NaN
19,219,Kalyan,83,85,89,87,87,88,NaN,NaN
20,226,Bhargavi,96,87,88,89,87,93,NaN,NaN
21,220,Charan,87,88,94,73,89,92,NaN,NaN
22,221,Arjun,89,99,95,92,65,77,NaN,NaN
23,222,Niha,65,87,96,91,74,88,NaN,NaN
24,223,Neeraja,74,85,87,93,94,99,NaN,NaN
25,224,Devi,94,88,82,86,95,87,NaN,NaN
26,225,Bindu,95,99,85,93,96,86,NaN,NaN
27,226,Bhargavi,96,87,88,89,87,93,NaN,NaN
28,227,Nandini,87,73,92,98,82,89,NaN,NaN
29,228,Syamala,82,92,77,87,85,98,NaN,NaN
30,229,Sumanth,85,91,82,89,88,87,NaN,NaN
31,230,Subhash,88,93,85,94,99,89,NaN,NaN
32,231,Devika,99,86,88,95,87,90,NaN,NaN
33,232,Isha,87,93,99,96,66,94,NaN,NaN
34,233,Apsara,73,89,87,87,88,95,NaN,NaN
35,234,Ankitha,66,94,85,82,77,78,NaN,NaN
36,235,Anuradha,84,95,88,85,99,92,NaN,NaN
37,236,Jeevana,85,78,99,88,59,77,NaN,NaN
38,237,Ganesh,96,92,87,92,60,92,NaN,NaN
39,238,Poorinima,92,77,73,77,56,69,NaN,NaN
40,239,Manjusha,91,90,92,97,70,68,NaN,NaN
41,240,Nikhitha,93,68,91,69,85,78,NaN,NaN

In [19]:
data.loc[1]

Roll No                     202
Name of the Student        Hari
C Language                   93
Java                         93
Python                       83
Machine Learning             78
Data Science                 93
Artificial Intelligence      70
Unnamed: 8                  NaN
Unnamed: 9                  NaN
Name: 1, dtype: object

In [20]:
data.loc[15]

Roll No                        216
Name of the Student        Lakshmi
C Language                      68
Java                            77
Python                          89
Machine Learning                85
Data Science                    77
Artificial Intelligence         87
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 15, dtype: object

In [21]:
data.loc[29]

Roll No                        228
Name of the Student        Syamala
C Language                      82
Java                            92
Python                          77
Machine Learning                87
Data Science                    85
Artificial Intelligence         98
Unnamed: 8                     NaN
Unnamed: 9                     NaN
Name: 29, dtype: object

In [22]:
data.loc[19,["Data Science"]]

Data Science    87
Name: 19, dtype: object

In [23]:
data.loc[10,["Python","Data Science","Artificial Intelligence"]]

Python                     87
Data Science               87
Artificial Intelligence    87
Name: 10, dtype: object

In [24]:
data.loc[0:10]

,Roll No,Name of the Student,C Language,Java,Python,Machine Learning,Data Science,Artificial Intelligence,Unnamed: 8,Unnamed: 9
0,201,Hema,86,86,91,95,86,69,NaN,NaN
1,202,Hari,93,93,83,78,93,70,NaN,NaN
2,203,Ram,89,89,95,92,89,86,NaN,NaN
3,204,Latha,98,98,96,77,98,90,NaN,NaN
4,205,Rani,87,87,87,92,87,96,NaN,NaN
5,206,Jyothi,89,89,82,69,89,86,NaN,=
6,207,Krishna,90,94,85,68,94,93,NaN,NaN
7,208,Raju,94,95,88,78,95,89,NaN,NaN
8,209,Suresh,95,96,99,91,96,98,NaN,NaN
9,214,Bhavya,69,92,93,82,92,96,NaN,NaN
10,210,Sandhya,78,87,87,83,87,87,NaN,NaN

In [25]:
data.iloc[0:10]

,Roll No,Name of the Student,C Language,Java,Python,Machine Learning,Data Science,Artificial Intelligence,Unnamed: 8,Unnamed: 9
0,201,Hema,86,86,91,95,86,69,NaN,NaN
1,202,Hari,93,93,83,78,93,70,NaN,NaN
2,203,Ram,89,89,95,92,89,86,NaN,NaN
3,204,Latha,98,98,96,77,98,90,NaN,NaN
4,205,Rani,87,87,87,92,87,96,NaN,NaN
5,206,Jyothi,89,89,82,69,89,86,NaN,=
6,207,Krishna,90,94,85,68,94,93,NaN,NaN
7,208,Raju,94,95,88,78,95,89,NaN,NaN
8,209,Suresh,95,96,99,91,96,98,NaN,NaN
9,214,Bhavya,69,92,93,82,92,96,NaN,NaN

In [26]:
data.loc[0:15,"C Language"]

0     86
1     93
2     89
3     98
4     87
5     89
6     90
7     94
8     95
9     69
10    78
11    92
12    77
13    92
14    69
15    68
Name: C Language, dtype: int64

In [27]:
data.loc[19:38,"Java"]

19    85
20    87
21    88
22    99
23    87
24    85
25    88
26    99
27    87
28    73
29    92
30    91
31    93
32    86
33    93
34    89
35    94
36    95
37    78
38    92
Name: Java, dtype: int64

In [28]:
data.loc[0:5,["Machine Learning","Python"]]

   Machine Learning  Python
0                95      91
1                78      83
2                92      95
3                77      96
4                92      87
5                69      82

UNDERSTANDING ILOCZ[](stop index excluded)

*data_frame.iloc[row_number,column_number]

*data_frame.iloc[row_start:row_stop,col_start:col_stop]

*data_frame.iloc[start:stop,"column_number"]

In [29]:
data.iloc[0:5]

,Roll No,Name of the Student,C Language,Java,Python,Machine Learning,Data Science,Artificial Intelligence,Unnamed: 8,Unnamed: 9
0,201,Hema,86,86,91,95,86,69,NaN,NaN
1,202,Hari,93,93,83,78,93,70,NaN,NaN
2,203,Ram,89,89,95,92,89,86,NaN,NaN
3,204,Latha,98,98,96,77,98,90,NaN,NaN
4,205,Rani,87,87,87,92,87,96,NaN,NaN

In [30]:
data.iloc[2,0]

203

In [31]:
data.iloc[0:5,0:7]

,Roll No,Name of the Student,C Language,Java,Python,Machine Learning,Data Science
0,201,Hema,86,86,91,95,86
1,202,Hari,93,93,83,78,93
2,203,Ram,89,89,95,92,89
3,204,Latha,98,98,96,77,98
4,205,Rani,87,87,87,92,87

In [32]:
data.iloc[0:5,1]

0     Hema
1     Hari
2      Ram
3    Latha
4     Rani
Name: Name of the Student, dtype: object

## Data Wrangling

# New Section

Data wrangling is the process of processing data to prepare it for use in the next step.

This processes include merging, grouping, and concatenation.

This kind of manipulation is often needed in data science to get your data in to a form that works well with whatever analysis or algorithms that you're going to put it through.

In [33]:
import pandas as pd

In [34]:
d1 = {
    'subject_id': ['1', '2', '3', '4', '5'],
    'student_name': ['John', 'Emily', 'Kate', 'Joseph', 'Dennis']
}

d2 = {
    'subject_id': ['4', '5', '6', '7', '8'],
    'student_name': ['Brian', 'William', 'Lilian', 'Grace', 'Caleb']
}

df1 = pd.DataFrame(d1, columns=['subject_id', 'student_name'])
df2 = pd.DataFrame(d2, columns=['subject_id', 'student_name'])

In [35]:
df1

  subject_id student_name
0          1         John
1          2        Emily
2          3         Kate
3          4       Joseph
4          5       Dennis

In [36]:
df2

  subject_id student_name
0          4        Brian
1          5      William
2          6       Lilian
3          7        Grace
4          8        Caleb

In [37]:
pd.merge(df1,df2 ,on='subject_id')

  subject_id student_name_x student_name_y
0          4         Joseph          Brian
1          5         Dennis        William

In [38]:
raw = {
    'Name': ['John', 'John', 'Grace', 'Grace', 'Benjamin', 'Benjamin', 'Benjamin',
        'Benjamin', 'John', 'Alex', 'Alex', 'Alex'],
    'Position': [2, 1, 1, 4, 2, 4, 3, 1, 3, 2, 4, 3],
    'Year': [2009, 2010, 2009, 2010, 2010, 2010, 2011, 2012, 2011, 2013, 2013, 2012],
    'Marks':[408, 398, 422, 376, 401, 380, 396, 388, 356, 402, 368, 378]
}
df3 = pd.DataFrame(raw)

In [39]:
df3

        Name  Position  Year  Marks
0       John         2  2009    408
1       John         1  2010    398
2      Grace         1  2009    422
3      Grace         4  2010    376
4   Benjamin         2  2010    401
5   Benjamin         4  2010    380
6   Benjamin         3  2011    396
7   Benjamin         1  2012    388
8       John         3  2011    356
9       Alex         2  2013    402
10      Alex         4  2013    368
11      Alex         3  2012    378

In [40]:
group = df3.groupby('Year')

In [41]:
group

In [42]:
group.get_group(2010)

       Name  Position  Year  Marks
1      John         1  2010    398
3     Grace         4  2010    376
4  Benjamin         2  2010    401
5  Benjamin         4  2010    380

In [43]:
print(pd.concat([df1, df2]))

  subject_id student_name
0          1         John
1          2        Emily
2          3         Kate
3          4       Joseph
4          5       Dennis
0          4        Brian
1          5      William
2          6       Lilian
3          7        Grace
4          8        Caleb

In [44]:
print(pd.concat([df1, df2],axis=1))

  subject_id student_name subject_id student_name
0          1         John          4        Brian
1          2        Emily          5      William
2          3         Kate          6       Lilian
3          4       Joseph          7        Grace
4          5       Dennis          8        Caleb

## Descriptive Statistics


describe() function gives the descriptive statistics for numerical columns, but the character columns are excluded.
The describe() method returns description of the data in the DataFrame.

If the DataFrame contains numerical data, the description contains these information for each column:

count - The number of not-empty values.\
mean - The average (mean) value.\
std - The standard deviation.\
min - the minimum value\
25% - The 25% percentile*.\
50% - The 50% percentile*.\
75% - The 75% percentile*.\
max - the maximum value.

*Percentile meaning: how many of the values are less than the given percentile.

In [ ]:
data = {
    'Name': ['John', 'Alice', 'Joseph', 'Alex'],
    'English': [64, 78, 68, 58],
    'Maths': [76, 54, 72, 64]
}

df = pd.DataFrame(data)
df.describe()

         English      Maths
count   4.000000   4.000000
mean   67.000000  66.500000
std     8.406347   9.712535
min    58.000000  54.000000
25%    62.500000  61.500000
50%    66.000000  68.000000
75%    70.500000  73.000000
max    78.000000  76.000000